apiVersion: apps/v1
kind: Deployment
metadata:
  name: loan-service
  namespace: loan-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loan-service
  template:
    metadata:
      labels:
        app: loan-service
    spec:
      containers:
        - name: loan-service
          image: your-docker-org/loan-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/loans
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name: APP_RISK_URL
              value: http://risk-service:8000
---
apiVersion: v1
kind: Service
metadata:
  name: loan-service
  namespace: loan-platform
spec:
  selector:
    app: loan-service
  ports:
    - port: 8080
      targetPort: 8080
