apiVersion: apps/v1
kind: Deployment
metadata:
  name: risk-service
  namespace: loan-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: risk-service
  template:
    metadata:
      labels:
        app: risk-service
    spec:
      containers:
        - name: risk-service
          image: your-docker-org/risk-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: risk-service
  namespace: loan-platform
spec:
  selector:
    app: risk-service
  ports:
    - port: 8000
      targetPort: 8000
